export const staticPlayers = [
    // Porteros (GK)
    {
        id: 1,
        jersey_number: 1,
        name: "Diego Jara",
        position: "GK",
        pace: 60,
        shooting: 25,
        passing: 45,
        dribbling: 30,
        defending: 85,
        physical: 75,
        image_url: "img/default_player.png"
    },
    {
        id: 2,
        jersey_number: 12,
        name: "Felipe Daza",
        position: "GK",
        pace: 62,
        shooting: 28,
        passing: 48,
        dribbling: 32,
        defending: 87,
        physical: 78,
        image_url: "img/default_player.png"
    },

    // Defensas (DF)
    {
        id: 3,
        jersey_number: 4,
        name: "Anibal Gonzales",
        position: "RW",
        pace: 80,
        shooting: 80,
        passing: 90,
        dribbling: 86,
        defending: 82,
        physical: 89,
        image_url: "img/default_player.png"
    },
    {
        id: 4,
        jersey_number: 6,
        name: "Tomas Aliste",
        position: "CB",
        pace: 75,
        shooting: 40,
        passing: 78,
        dribbling: 60,
        defending: 88,
        physical: 85,
        image_url: "img/default_player.png"
    },
    {
        id: 5,
        jersey_number: 19,
        name: "Cristian Vargas",
        position: "LB",
        pace: 70,
        shooting: 35,
        passing: 75,
        dribbling: 55,
        defending: 89,
        physical: 90,
        image_url: "img/default_player.png"
    },
    {
        id: 6,
        jersey_number: 8,
        name: "Esteban Vega",
        position: "RW",
        pace: 79,
        shooting: 60,
        passing: 77,
        dribbling: 72,
        defending: 80,
        physical: 82,
        image_url: "img/default_player.png"
    },
    {
        id: 7,
        jersey_number: 13,
        name: "Sergio Abarca",
        position: "LB",
        pace: 78,
        shooting: 45,
        passing: 76,
        dribbling: 62,
        defending: 87,
        physical: 84,
        image_url: "img/default_player.png"
    },
    {
        id: 8,
        jersey_number: 26,
        name: "Mauricio Allendes",
        position: "CAM",
        pace: 85,
        shooting: 60,
        passing: 72,
        dribbling: 70,
        defending: 79,
        physical: 75,
        image_url: "img/default_player.png",
    },

    // Mediocampistas (MC)
    {
        id: 9,
        jersey_number: 5,
        name: "Carlos Nuñez",
        position: "RB",
        pace: 65,
        shooting: 70,
        passing: 85,
        dribbling: 75,
        defending: 78,
        physical: 80,
        image_url: "img/default_player.png"
    },
    {
        id: 10,
        jersey_number: 7,
        name: "Andres Vargas",
        position: "RB",
        pace: 78,
        shooting: 75,
        passing: 82,
        dribbling: 80,
        defending: 75,
        physical: 85,
        image_url: "img/default_player.png"
    },
    {
        id: 11,
        jersey_number: 24,
        name: "Jesus Duran",
        position: "RW",
        pace: 75,
        shooting: 72,
        passing: 86,
        dribbling: 84,
        defending: 70,
        physical: 75,
        image_url: "img/default_player.png"
    },
    {
        id: 12,
        jersey_number: 20,
        name: "Fabian Campos",
        position: "RW",
        pace: 72,
        shooting: 78,
        passing: 83,
        dribbling: 81,
        defending: 68,
        physical: 70,
        image_url: "img/default_player.png"
    },
    {
        id: 13,
        jersey_number: 17,
        name: "Nicolas Villar",
        position: "RW",
        pace: 70,
        shooting: 80,
        passing: 85,
        dribbling: 88,
        defending: 40,
        physical: 60,
        image_url: "img/default_player.png"
    },
    {
        id: 14,
        jersey_number: 16,
        name: "Joshua Correo",
        position: "CAM",
        pace: 82,
        shooting: 76,
        passing: 80,
        dribbling: 86,
        defending: 35,
        physical: 58,
        image_url: "img/default_player.png"
    },

    // Delanteros (FW)
    {
        id: 15,
        jersey_number: 10,
        name: "Benjamin Lopez",
        position: "ST",
        pace: 88,
        shooting: 95,
        passing: 92,
        dribbling: 96,
        defending: 38,
        physical: 65,
        image_url: "img/default_player.png"
    },
    {
        id: 16,
        jersey_number: 9,
        name: "Ignacio Perez",
        position: "CF",
        pace: 85,
        shooting: 86,
        passing: 70,
        dribbling: 82,
        defending: 45,
        physical: 70,
        image_url: "img/default_player.png"
    },
    {
        id: 17,
        jersey_number: 11,
        name: "Tomas Palma",
        position: "LW",
        pace: 80,
        shooting: 82,
        passing: 88,
        dribbling: 87,
        defending: 40,
        physical: 70,
        image_url: "img/default_player.png"
    },
    {
        id: 18,
        jersey_number: 22,
        name: "Roberto Perez",
        position: "RW",
        pace: 80,
        shooting: 88,
        passing: 65,
        dribbling: 78,
        defending: 40,
        physical: 80,
        image_url: "img/default_player.png"
    }
];